CREATE TABLE MEMOS.FOLDER(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION TEXT,
    AUTHOR VARCHAR(64) NOT NULL,
    PUBLIC_ACCESS BOOLEAN DEFAULT TRUE,
    UNIQUE (NAME, AUTHOR)
);

CREATE TABLE MEMOS.MEMO(
    ID SERIAL PRIMARY KEY,
    FOLDER_NAME VARCHAR(128) NOT NULL,
    AUTHOR VARCHAR(64) NOT NULL,
    FRONT_TEXT TEXT NOT NULL,
    BACK_TEXT TEXT NOT NULL,
    TAGS TEXT,
    FOREIGN KEY (FOLDER_NAME, AUTHOR) REFERENCES MEMOS.FOLDER(NAME, AUTHOR)
);

CREATE TABLE MEMOS.USER(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL
);